modLoader="kotlinforforge"
loaderVersion="[2,)"
# modLoader="javafml"
# loaderVersion="[37,)"
license="${Mod.LICENSE}"
issueTrackerURL="${Mod.Contact.ISSUES}"

[[mods]]
modId="${Mod.ID}"
version="${Mod.VERSION}"
displayName="${Mod.NAME}"
logoFile="${Mod.ID}.png"
authors="${Mod.AUTHOR}"
description='''
${Mod.DESCRIPTION}
'''

[[dependencies.${Mod.ID}]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"

[[dependencies.${Mod.ID}]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.${Mod.ID}]]
modId="cloth_config"
mandatory=false
versionRange="[5.0.38,)"
ordering="NONE"
side="CLIENT"
