#if ($language == "java")
  #set ($modLoader = "javafml")
  #set ($loaderVersion = "[39,)")
#elseif ($language == "kotlin")
  #set ($modLoader = "kotlinforforge")
  #set ($loaderVersion = "[3,)")
#end
modLoader="${modLoader}"
loaderVersion="${loaderVersion}"
license="${Mod.LICENSE}"
issueTrackerURL="${Mod.Contact.ISSUES}"

[[mods]]
modId="${Mod.ID}"
version="${Mod.VERSION}"
displayName="${Mod.NAME}"
logoFile="${Mod.ID}.png"
authors="${Mod.AUTHOR}"
description='''
${Mod.DESCRIPTION}
'''

[[dependencies.${Mod.ID}]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"

[[dependencies.${Mod.ID}]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"

[[dependencies.${Mod.ID}]]
modId="cloth_config"
mandatory=false
versionRange="[5.0.38,)"
ordering="NONE"
side="CLIENT"
